import CustomNavbar from '@/components/CustomNavbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import UserContext from './context/userContext'
import UserProvider from './context/userProvider'

//export const metadata = {
 // title: 'Create Next App',
  //description: 'Generated by create next app',the
//}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <UserProvider>
       <CustomNavbar/>
        <ToastContainer/>
        
       <div className='mt-0'>{children}</div>
        <Footer/>
       </UserProvider>
        </body>
    </html>
  )
}
